name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# App version
version: 1.0.0+1

environment:
  # sqflite 2.4.2 needs Dart >=3.7.0
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management & navigation
  get: ^4.7.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7

  # Layout & responsive UI
  flutter_screenutil: ^5.9.3

  # Networking & data
  dio: ^5.7.0
  

  # Notifications & connectivity
  fluttertoast: ^9.0.0
  pusher_channels_flutter: ^2.5.0  # Dart 3 compatible
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^7.0.0  # uncomment if needed

  # Icons (only once)
  cupertino_icons: ^1.0.8

  # Localization (3rd-party helper package)
  flutter_localization: ^0.3.3

  # Official Flutter localization bundle
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.2
  geolocator: ^14.0.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  syncfusion_flutter_pdfviewer: ^31.2.12
  geocoding: ^4.0.0
  country_picker: ^2.0.27
  country_state_city: ^0.1.6
  country_state_city_picker: ^1.2.8
  # And if you need formatting (dates, numbers, etc.), you can also add:
  # intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
